name: oktane_pos
description: "Oktane POS - Sistema de punto de venta"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Local Database (Drift/SQLite)
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.8.3

  # Networking
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  supabase_flutter: ^2.5.0

  # Persistencia Local Ultrarrápida y Bloqueo de Pantalla
  shared_preferences: ^2.2.2
  wakelock_plus: ^1.2.8

  # JSON Serialization
  json_annotation: ^4.9.0

  # Hardware / Media
  mobile_scanner: ^7.0.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.1

  # PDF and Printing
  pdf: ^3.10.8
  printing: ^5.11.1
  qr_flutter: ^4.1.0
  print_bluetooth_thermal: ^1.1.2
  esc_pos_utils_plus: ^2.0.4

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  drift_dev: ^2.14.0
  json_serializable: ^6.7.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/faceplates/